### ISSUE TITLE
Create MacOS for both intel and  Apple Silicon for latest version of Python for release candidates

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#747]
similar to #738 but for macos (both intel and apple silicon).

#### Why 

Historically there have been some packaging issues with older versions of Python with Apple silicon.

Also there is to consider that there could be some file system issues that come up due to things like MacOS system permissions for writing to disk.

Testing for it will give us better insight on how to document for it as well.

#### Why only the latest version for release candidates

Testing on MacOS uses 10x the free resources that linux does and 5x that of windows... These should only be done on  

#### What to do

There are 2 steps in the GitHub action under `tests.yaml`. Perhaps we can make a third that only runs when there is a release pending or part of the `publish.yaml`

**Comment by OsamaRab3** [comment]
I am currently working on this issue  While running the GitHub Actions workflow, I encountered the following erro
![image](https://github.com/user-attachments/assets/e8c2e4d2-5574-493c-9201-c532db0371e6)


It seems there is a conflict with the artifact name during the upload process. I believe this is happening because the artifact name is not unique for each workflow run, I wanted to confirm if this is correct ?
