### ISSUE TITLE
[Bug]: Auto Format and Lint no longer working 

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#832]
### Summary Of Actions

When a PR is submitted and it hasn't been linted the test fails but only after trying to make the changes and push them to the PR.

### Operating System

Macos

### What Python Version are you using?

Python 3.12

### Have you installed Plugins/Themes/Custom Parsers?

N/A

### What did you enter to get the output that you received?

```Shell
This was the response based on a PR.
```

### Output

```Shell
Run if [ -n "$(git status --porcelain)" ]; then
  if [ -n "$(git status --porcelain)" ]; then
    git config --global user.name "Ruff"
    git config --global user.email "ruff-action@users.noreply.github.com"
    git add -A
    git commit -m "Format and lint with Ruff"
    git push origin HEAD:caching-workflows
  fi
...
remote: Permission to render-engine/render-engine.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/render-engine/render-engine/': The requested URL returned error: 403
Error: Process completed with exit code 12[8](https://github.com/render-engine/render-engine/actions/runs/11504893660/job/32100071862?pr=831#step:9:8).
```
```

**Comment by kjaymiller** [comment]
It's hard to tell how we should solve this problem. 

It boils down to a small developer philosophy question.

Should a bot have the ability to modify your code without your involvement.

Most people would say no to this. 

The solution in that case is to likely adopt something like pre-commit and then add the linting rules to it. This would not only allow for a check during the PR but give people a way to pre-solve these issues by running pre-commit themselves. they can then choose to push those changes themselves.

We can also ensure at that point that all files have been linted to our expecations without force pushing to someone's PR.

**Comment by kjaymiller** [comment]
@john0isaac what do you think?

**Comment by john0isaac** [comment]
I had a similar issue it will only work for PRs created from the same origin not from forks.

I found out that it was a permission issue because it's trying to push commit to a forked repo not our repo.
A solution I previously did was by checking if PR from a fork or not
if it's from a fork just log the errors in the workflow run or as a comment on the PR 
if it's from "US" (PR created from a branch on the same repo) then we can push the fixes safely

I think we can just remove the committing step and exit the workflow with a failure status if there are any changes in the files

particularly do this

```
- name: Check Status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi
```
